version: '2'
services:
  web:
    container_name: testlink_web
    depends_on:
        - db
    restart: always
    image: bitnami/testlink:latest
    ports:
        - 8080:80
    volumes:
        - ./tmp/config_db.inc.php.tpl:/root/.nami/components/com.bitnami.testlink/templates/config_db.inc.php.tpl
    environment:
        TESTLINK_DATABASE_NAME: testlinkdb
        TESTLINK_DATABASE_USER: testlink
        TESTLINK_DATABASE_PASSWORD: testlinkrocks
        MARIADB_HOST: db
        MARIADB_PORT_NUMBER: 5432
  
  db:
    image: postgres:9-alpine
    environment:
      POSTGRES_DB: testlinkdb
      POSTGRES_USER: testlink
      POSTGRES_PASSWORD: testlinkrocks
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
  uploads:
