apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins
  namespace: k8s-project
  annotations:
    kubernetes.io/ingress.class: k8s-project-ingress
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /jenkins
        backend:
          serviceName: k8s-project-jenkins
          servicePort: 8080