apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: testlink
  namespace: k8s-project
  annotations:
    kubernetes.io/ingress.class: k8s-project-ingress
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
spec:
  rules:
  - http:
      paths:
      - path: /testlink/?(.*)
        backend:
          serviceName: k8s-project-testlink
          servicePort: 80