image:
  tag: 4.32.0
externalDatabase:
  url: "jdbc:mysql://k8s-project-postgresql.k8s-project/gitbucket?useUnicode=true&characterEncoding=utf8"
configFromMap:
  enabled: true
  name: k8s-project-config
